---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-install
  namespace: metallb-system
spec:
  addresses:
  - 172.17.0.0/16
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
